# Generated by Django 2.2.5 on 2020-01-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('view_count', models.IntegerField(verbose_name='View Count')),
                ('root_category', models.CharField(max_length=64, verbose_name='Root Category')),
                ('category', models.CharField(max_length=64, verbose_name='Category')),
                ('image', models.TextField(verbose_name='Image')),
                ('publish_time', models.TimeField(verbose_name='Publish Time')),
                ('publish_date', models.DateField(verbose_name='Date')),
                ('lead', models.TextField(verbose_name='Lead Text')),
            ],
        ),
    ]
