# Generated by Django 2.2.5 on 2020-01-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'NEWS'},
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_date',
            field=models.CharField(max_length=16, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.CharField(max_length=16, verbose_name='Publish Time'),
        ),
    ]
